strictness: medium
doc-warnings: true
max-line-length: 100
inherits:
  - default
ignore-paths:
  - venv
  - .venv
  - build
  - docs
  - tests/Dicom
ignore-patterns:
  - .*__init__\.py$
pydocstyle:
  run: false
