[tool.poetry]
name = "srmip"
version = "0.0.4"
description = "Python library for Medical Image Processing (MIP)."
authors = ["G. Palazzo, M.G. Ubeira-Gabellini"]
license = "GNU Lesser General Public License v2.1"
readme = "README.md"
repository = "https://github.com/pymaitre/srmip"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.26.4"
pydicom = "^2.4.4"
simpleitk = "^2.4.1"
scikit-image = "^0.24.0"
matplotlib = "^3.9.4"
bidict = "^0.23.1"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.1.0"
sphinx-rtd-theme = "^3.0.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
prospector = "^1.10.3"
pytest = "^8.3.3"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = ['--cov=srmip']
