[tool.poetry]
name = "resmip"
version = "0.0.5"
description = "Python library for Medical Image Processing (MIP)."
authors = ["G. Palazzo, M.G. Ubeira-Gabellini"]
license = "GNU Lesser General Public License v2.1"
readme = "README.md"
repository = "https://github.com/pymaitre/resmip"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^2.0.0"
pydicom = "^3.0.1"
simpleitk = "^2.4.1"
scikit-image = "^0.24.0"
matplotlib = "^3.10.7"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "^7.4.7"
sphinx-rtd-theme = "^3.0.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
prospector = "^1.16.1"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
ruff = "^0.14.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = ["--cov=resmip"]

[tool.pylint.DESIGN]
max-args = 8
max-locals = 18

[tool.ruff.lint]
extend-select = ["D"]

[tool.ruff.lint.pydocstyle]
convention = "google"
