name: Test

on:
  push:
  pull_request:

jobs:
  build-windows:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [windows-2022, ubuntu-20.04]
        python-version: [3.9]

    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install

      - name: Control code structure
        run: |
          poetry install --with test
          poetry run prospector --profile extras/profile.yaml
          poetry run pylint tests

      - name: Build and test docs
        run: |
          python -m pip install sphinx sphinx-rtd-theme
          cd docs
          make html
          make doctest

      - name: Test code
        run: |
          poetry install --with test
          poetry run pytest
